version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.backend
      target: dev
    environment:
      DEBUG: 1
      VERSION: dev
      UVICORN_RELOAD_DIR: /
    restart: on-failure
    volumes:
      - type: bind
        source: ./backend
        target: /code/

  frontend:
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.frontend
      target: dev
    restart: on-failure
    environment:
      VERSION: "dev"
    ports:
     - 127.0.0.1:8080:8080
    volumes:
      - type: bind
        source: ./frontend/src
        target: /code/src

  proxy:
    image: nginx:alpine
    ports:
      - 127.0.0.1:5000:8080
    depends_on:
      - backend
      - frontend
    volumes:
      - type: bind
        source: ./Dockerfiles/nginx.conf.dev
        target: /etc/nginx/conf.d/default.conf
