FROM node:14-alpine as build

RUN yarn global add @quasar/cli

COPY ./frontend/package.json /package.json

WORKDIR /
RUN yarn install


COPY ./frontend /code
RUN mv /node_modules /code/
WORKDIR /code

RUN quasar build

FROM nginx:alpine

COPY --from=build /code/dist/spa/ /usr/share/nginx/html/
COPY ./Dockerfiles/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
