name: Publish Docker Image
on:
  push:
    branches:
      - master
      - develop
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'ScilifelabDataCentre/lunch-menu'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta - backend
        id: meta-backend
        uses: docker/metadata-action@v3
        with:
          images: |
            scilifelabdatacentre/menu-backend
            ghcr.io/scilifelabdatacentre/menu-backend
      - name: Docker meta - frontend
        id: meta-frontend
        uses: docker/metadata-action@v3
        with:
          images: |
            scilifelabdatacentre/menu-frontend
            ghcr.io/scilifelabdatacentre/menu-frontend
      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile.backend
          context: .
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile.frontend
          context: .
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
